### PR TITLE
Make Lutris Run Again

### PR DESCRIPTION
**Pull request by julianschacher**
Fixes: https://github.com/flathub/net.lutris.Lutris/issues/91

This fixes the `AttributeError: type object 'TreeModelSort' has no attribute 'sort_new_with_model'` error (https://github.com/flathub/net.lutris.Lutris/issues/91 and https://github.com/lutris/lutris/issues/2554) by applying the fix from https://github.com/lutris/lutris/pull/2558 as a patch (you can get a patch from a PR by adding `.patch` at the end of the url).

Once the change introduced in https://github.com/lutris/lutris/pull/2558 is included in a new Lutris version, the changes made in this PR can be reverted, when upgrading to that new Lutris version.
This version will probably be `0.5.5` (see https://github.com/lutris/lutris/issues/2554).

### CODE REVIEW

**Comment by RobLoach** [comment]
Would you mind pushing this up as a Pull Request upstream?

**Comment by julianschacher** [comment]
> Would you mind pushing this up as a Pull Request upstream?

What do you mean by "upstream"?

**Comment by RobLoach** [comment]
Mind pushing as a Pull Request up to https://github.com/lutris/lutris ?

**Comment by julianschacher** [comment]
This PR uses a change, which already is in the https://github.com/lutris/lutris master branch, but isn't in a release yet. I made this PR to temporarily patch this Flatpak, so that it works again.
Once this change is in an upstream release (which should be the `0.5.5` release), the changes made with this PR can be reverted.

**Comment by RobLoach** [comment]
Ah, thanks for the clarification :+1:
